name: Linter

on:
  push:
    branches: [ 'master', 'main']

  pull_request:
    branches: [ 'master', 'main']

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter
        uses: super-linter/super-linter@v4
        env:
          DEFAUL_BRANCH: master
          GITHUB_TOKEN: ${{ github.token }}