name: Build Windows executable

on:
  push:
    branches: [ 'main', 'master']

jobs:
  build:
    name: Create executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Runs PyInstaller action
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: post_processing_tool

      - uses: actions/upload-artifact@v4
        with:
          name: crece-post-processing-tool
          path: post_processing_tool/dist/windows