name: Build Windows executable

on:
  push:
    branches: [ 'main', 'master']

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: |
        pip install -r post_processing_tool/requirements.txt
        pip install -r post_processing_tool/dev-requirements.txt      

    - name: Run pyinstaller
      run: |
        pyinstaller post_processing_tool/main.spec

    - uses: actions/upload-artifact@v4
      with:
        name: crece-post-processing-tool-${{ matrix.os }}
        path: post_processing_tool/dist/
