name: Build Windows executable

on:
  pull_request:
    branches: ['master']
  push:
    branches: [ 'main', 'master']

jobs:
  build:
    name: Create executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Debug
      - run: ls -lah

      - name: Runs PyInstaller action
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - uses: actions/upload-artifact@v4
        with:
          name: crece-post-processing-tool
          path: post_processing_tool/dist/windows