name: Sync contacts

on:
  workflow_dispatch:
    inputs:
      syncIntervalWeeks:
        description: Sync contacts from last n weeks
        required: false
        default: 2
        type: string

  schedule:
    - cron: '0 3 * * 1' # UTC

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r post_processing_tool/requirements.txt

    - name: Generate csv
      env:
        MAILCHIMP_DOMAIN: ${{ secrets.CRECE_MAILCHIMP_DOMAIN }}
        MAILCHIMP_LIST_ID: ${{ secrets.CRECE_MAILCHIMP_LIST_ID }}
        MAILCHIMP_API_KEY: ${{ secrets.CRECE_MAILCHIMP_TOKEN }}
        MAILCHIMP_USERNAME: ${{ secrets.CRECE_MAILCHIMP_USER }}
        CRECE_SYNC_INTERVAL_WEEKS: ${{ inputs.syncIntervalWeeks || 2 }}
      run: |
        mkdir results
        python main.py -c -d -o ./results -r ./templates/report_template.html.j2
        ls results

    - name: Send csv
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.MAIL_ADDRESS }}
        password: ${{ secrets.CRECE_SENDER_APP_PWD }}
        subject: "CRECE NUEVOS: Sync semanal"
        to: ${{ secrets.CRECE_RECIPIENT_EMAIL }}
        cc: "torresmoisesa@gmail.com"
        from: "botcrece"
        html_body: "file://index.html"
        reply_to: torresmoisesa@gmail.com
        ignore_cert: true
        attachments: "./results/*csv,format_hist_img.png,format_cities_img.png"
        priority: low
