name: Test macos

on:
  pull_request:
    branches: [ 'main', 'master']

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r post_processing_tool/requirements.txt
        pip install -r post_processing_tool/dev-requirements.txt

    - name: Run pyinstaller
      run: |
        pyinstaller post_processing_tool/main.spec

    - name: Set executable bit
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        chmod -R +x dist/* 
        ./dist/post_process_tool

    - uses: actions/upload-artifact@v4
      with:
        name: crece-post-processing-tool-${{ matrix.os }}
        path: dist/**
